name: CSS environment variables
description: The `env()` CSS function inserts an environment variable from the device with an optional fallback value.
spec: https://drafts.csswg.org/css-env-1/#env-function
caniuse: css-env-function
group: environment-variables
compat_features:
  - css.properties.custom-property.env
